apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  name: slo-k8s-istio-availability
  namespace: monitoring
  labels:
    release: prometheus
    team: platform-engineering
    env: prod
spec:
  service: "k8s-istio"
  labels:
    cluster: "prod-us-east-2"
    component: "kubernetes"
    team: "platform-engineering"
  slos:
    - name: "istiod-availability"
      objective: 99.99
      description: "Warn that istiod replicas are at an insufficient level."
      labels:
        category: availability
      sli:
        events:
          errorQuery: sum(rate(istio_requests_total{response_code=~"(5..|429)"}[{{.window}}]))
          totalQuery: sum(rate(istio_requests_total[{{.window}}]))
      alerting:
        name: K8sIstioDAvailabilityAlert
        labels:
          category: "availability"
        annotations:
          runbook: "https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubeapilatencyhigh"
        pageAlert:
          labels:
            severity: critical
        ticketAlert:
          labels:
            severity: warning
    - name: "istiod-convergence"
      objective: 99.995
      description: "Istio config changes pushed to a proxy sidecar converge in less than 0.5 seconds 99.995% of the time."
      labels:
        category: convergence
      sli:
        events:
          # https://prometheus.io/docs/practices/histograms/#:~:text=rate(http_request_duration_seconds_count%5B5m%5D)-,Apdex%20score,-A%20straight%2Dforward
          errorQuery: sum(rate(istio_agent_pilot_proxy_convergence_time_bucket{le="0.5"}[{{.window}}])) / sum(rate(istio_agent_pilot_proxy_convergence_time_count{}[{{.window}}]))))
          totalQuery: sum(rate(istio_agent_pilot_proxy_convergence_time_count[{{.window}}]))
      alerting:
        name: IstioConfigConvergenceAlert
        labels:
          category: "convergence"
        annotations:
          summary: "Slow convergence detected"
        pageAlert:
          labels:
            severity: critical
        ticketAlert:
          labels:
            severity: warning
