{
 "title": "Cohort platform-core-services Alerts",
 "tags": [
  "PE-Team",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Core-Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Node Network Receive Bytes",
   "type": "timeseries",
   "description": "Kubernetes Instance Node Network receive Bytes (Average By Instance)",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container!=\"\"}[5m])) by (node)"
    }
   ]
  },
  {
   "title": " Instance Node CPU Usage",
   "type": "timeseries",
   "description": "Kubernetes Instance Node CPU Utilization (Average by Instance)",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (node)\n"
    }
   ]
  },
  {
   "title": "EC2 CPU Utilization per instance (Average%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "auto",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "EC2 Inbound network traffic per instance (bytes/sec, period 300)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 10 },
   "targets": [
    {
     "dimensions": { "InstanceId": "*" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "core-services pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{app_kubernetes_io_name=\"kube-state-metrics\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"metrics-server\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"grafana-agent-logs\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"grafana-agent-traces\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"prometheus-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Monitoring Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Prometheus Monitor Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"prometheus\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Grafana Log Agent Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"grafana-agent-logs\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Grafana Traces Agent Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"grafana-agent-traces\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}